### ISSUE TITLE
TP3 Aprobado: 6 (Seis)

### ISSUE THREAD

**Issue by egenender** [JoaquinLonardi/TDA-TP3#1]
### Elementos a reentregar en un anexo:

> los v´ertices pasan a ser el universo de elementos U que pueden ser inclu´ıdos en
> los subsets y los subsets S del universo U los podemos armar viendo los adyacentes de > cada v´ertice y chequeando si un par de adyacentes son tambi´en adyacentes entre s´ı.

La reducción es incorrecta. Antes que nada, no se están  relacionando los problemas de decisión y no hay mención al valor de K. Sin el valor de K, para cualquier problema siempre existe Vertex Cover o Hitting Set de tamaño arbitrario.
Además, la transformación está sub-especificada, para la descripción dada y el grafo de ejemplo, la instancia mostrada a continuación también cumple con el esquema:
- {1,2,3,4}, {1,2,4,5}, {1,3}, {1,2,4}, {2,5}

> **Por cada v´ertice** recorremos sus adyacentes
> y, si un adyacente a del v´ertice v es a su vez adyacente a otro adyacente a
> ′ de v, estos v´ertices se agregan a un set.

En ese caso entonces no se entiende por qué en el ejemplo mostrado con 5 vértices se construye una instancia con 3 subsets

Ahora propongo un grafo y siguiendo las instrucciones para hacer la transformación.
Sea el grafo con vértices V={1,2,3,4,5,6,7}
y aristas: {1,4}, {1,5}, {1,2}, {2,3}, {3,6}, {3,7}

Para el problema de Hitting Set, U={1,2,3,4,5,6,7}
y los subsets se construyen viendo cada Vértice y agregando sus adyacentes
según 1 {1,2,4,5}
según 2 {1,2,3}
según 3 {2,3,6,7}
según 4 {1,4}
según 5 {1,5}
según 6 {3,6}
según 7 {3,7}

Nos preguntamos como problema de decisión si existe un VC de tamaño a lo sumo k=2.
En el grafo no existe Vertex Cover de tamaño 2. El mínimo es 3.

Le preguntamos a la caja negra de Hitting Set si existe de tamaño a lo sumo k=2
Existe, la respuesta es que sí. En particular podemos ver cuál es, es {1,3}

Queda la muestra de que el resultado de la caja negra de Hitting Set no es de utilidad para el problema de Vertex Cover.

> Efectividad de la aproximaci´on

En esta sección hay una tabla que no llega a representar correctamente yo estimo, ya que para todos los casos b vale 48, 49 o 50. Si se variaron los tamaños de los subconjuntos, ¿por qué el valor de b siempre es tan parecido?
Está bueno que esté la tabla, pero asegurarse de estar tomando correctamente el valor de b.

> agregar el siguiente análisis de la consigna, que está faltando en el informe

Realizar también mediciones que contemplen volúmenes de datos ya inmanejables para el algoritmo exacto, a fin de corroborar empíricamente la cota calculada anteriormente.

### Resto de las correcciones:

> Se propone el siguiente certificador:

Verificar que el tamaño de la solución es a lo sumo k

> Por lo tanto, la complejidad de este certificador se mantendr´ıa en un tiempo polinomial, siendo este particularmente O(|sets| ∗ |solucion|)

Si se quiere una cota que dependa de los parámetros del problema, el tamaño de la solución se puede acotar por la cantidad de elementos del problema, y sigue siendo polinomial

> Soluci´on por Backtracking

Hay oportunidades de poda remanentes.
Evitar el uso de elementos que no hittean nuevos subsets. Agregarlo tiene exactamente el mismo resultado que no agregarlo, pero usando un elemento más.
Considerar si con los jugadores que quedan podrán hittearse todos los subsets.
Incluso antes de llegar al último jugador, si la solución ya es válida entonces se puede devolver. Esto se debe a que seguir avanzando por esta rama solamente implica agregar más jugadores, no podrá haber una mejor solución.

> Soluci´on del problema: como ya vimos, la programaci´on lineal continua es en general
> polinomial con respecto a las variables. Por lo tanto, la complejidad de esta secci´on es O(n)

Si bien el método Simplex se comporta polinomial, no es lineal O(n).

> Sabemos que el valor de a puede ser menor que el valor de z(I). Definimos la relaci´on

Hay que explicar por qué se da este fenómeno, debido a que se relajan restricciones.

**Comment by JoaquinLonardi** [comment]
Hola profe, tenía una pregunta. No sé si estoy entendiendo mal, pero si analizo el grafo que utilizas de contrajemplo para la reducción ("Sea el grafo con vértices V={1,2,3,4,5,6,7} y aristas: {1,4}, {1,5}, {1,2}, {2,3}, {3,6}, {3,7}") yo veo un vertex cover de k = 2, exactamente igual al que daría el Hitting Set = {1, 3}. 
![image](https://github.com/JoaquinLonardi/TDA-TP3/assets/65740896/eca577eb-ef49-4e9c-8536-e2a3fce5c0f9)
No logro verlo como un contraejemplo de la reducción que yo plantée. Hay algo que no estoy viendo?

**Comment by egenender** [comment]
El procedimiento que estás mostrando en este mensaje no es el mismo que aplicaste en la entrega del informe.
Sin ir más lejos, en el informe tenés un subset de {1,2,4}, mientras que en el mensaje que enviás es imposible tener un subset de más de 2 elementos.

La metodología que enviás en el mensaje se ve correcta, pero debe ser entonces aplicada en el informe del TP

**Comment by egenender** [comment]
Trataré de hacer otro ejemplo para este texto expuesto en el Informe:

> Luego, recorremos los v´ertices del grafo. Por cada v´ertice recorremos sus adyacentes
> y, si un adyacente a del v´ertice v es a su vez adyacente a otro adyacente a
> ′ de v, estos v´ertices
> se agregan a un set

Sea el grafo con vértices V={1,2,3}
y aristas: {1,2}, {2,3}, {3,1}

Es decir, es un grafo de 3 vértices donde todos se conectan con todos.

Vamos, según lo que dice el texto, recorrer los vértice.
Por cada vértice, por ejemplo el 1, recorremos sus adyacentes
Si un adyacente "a" (ej el 2) es  a su vez adyacente a otro adyacente " a' " de v, se agregan a un set

Tenemos entonces el set {1,2,3}

Analizar los otros vértices también nos dará siempre la solución {1,2,3}

Para cubrir ese/esos subsets, alcanza con un solo elemento, es decir, existe solución para k=1

Sin embargo, no existe solución para el problema de Vertex Cover con k=1

**Comment by egenender** [comment]
> los v´ertices pasan a ser el universo
> de elementos U que pueden ser inclu´ıdos en los subsets y los subsets S del universo U pasan a
> ser el conjunto de aristas. Es decir, U = V y S = E.

Tener en cuenta que la definción de subconjuntos no es equivalente a como se definen las aristas.
Es decir, para la arista a1 que une a u y v, no es trivial decir que esa arista equivale a un subconjunto que incluye a {u,v}. Por lo descrito se entiende, pero idealmente hay que detallar la transformación.
